root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server && go build -o ./tmp/seed ./cmd/seed"
  bin = "./tmp/server"
  full_bin = "./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 500

[log]
  time = true

[color]
  build = "yellow"
  runner = "green"
  watcher = "cyan"
  app = "white"

[misc]
  clean_on_exit = true
